### PR TITLE
Convert to Jekyll

### PR DESCRIPTION
**Pull request by endreman0**
I'm going to leave this to you, @BenP51 to merge in. While there is a very minimal change to the front-end, the back-end is essentially rewritten from scratch.
Jekyll is an awesome blog generator, or template engine, or something (I don't remember what the actual description is). Basically, it allows you to do a lot of neat things with HTML that you would have to turn to PHP to do otherwise. (And Github Pages doesn't support PHP, unfortunately.)
Jekyll 101: Jekyll allows you to:
 - Define front matter. This is the key-value assignments fenced in by triple-dashes at the top of each page. You can define values here and reference them anywhere in the file using `{{ page.<key> }}`. You can also define things in `_config.yml` (which looks remarkably similar to the front-matter) and reference them through `{{ site.<key> }}`.
 - Define layout pages. Jekyll will find the file in the `_layouts` folder with the name that you put in the `layout` attribute of the front matter. So if you put `layout: page`, Jekyll would go find `_layouts/page.html` and insert the page's content into that layout.
 - Perform if-else, for, etc. For example, the `list` iterates over all of the pages that contain the given folder name in their URL. (The folder name is stored in the front-matter of each subject's `index.html` page. That's the other great thing about front-matter: you can pass values from page to template.)
 - There's a 75% chance I'm forgetting something, so you can find out what in [the official docs](http://jekyllrb.com/).

If you happen to have a Mac or Linux box, you can also download Jekyll and build the site locally before pushing. Unfortunately, Jekyll isn't compatible with Windows, so I just have to commit and view through the web browser. (Trial-and-error with this method turns into a lot of commit spam, so I'll primarily work in my fork to avoid assaulting your inbox.)

### CODE REVIEW

**Comment by endreman0** [comment]
Oh, also made a Twitter icon at the bottom of every page. Trade-off for the selected item in the menu not showing up, because I can't figure that out right now.

**Comment by endreman0** [comment]
Example commit spam. All 10 of those commits, just to make the current page's item in the navbar light up again. And it still only works for the subject home page, not [the](http://endreman0.github.io/HomeHelp.github.io/Chemistry/) [pages](http://endreman0.github.io/HomeHelp.github.io/Chemistry/BalancingEquations.html) [with](http://endreman0.github.io/HomeHelp.github.io/Chemistry/ElementalCalculator.html) [actual](http://endreman0.github.io/HomeHelp.github.io/Chemistry/Energy&States.html) [answers](http://endreman0.github.io/HomeHelp.github.io/Chemistry/Energy&States2.html).

**Comment by endreman0** [comment]
More commit spam! This batch was shorter and more effective though: I fixed the link highlighting (albeit after removing the `Home` link), and fixed the Elemental Calculator. So, for now, I declare this PR ready to merge. On your mark, @BenP51.

**Comment by BenP51** [comment]
I will try to get this working, but as of now it says I cant merge it. Using command line rn

**Comment by BenP51** [comment]
Pretty sure its fixed. Tell me if its right.
If it is, I'll close. Thanks!

**Comment by endreman0** [comment]
The commits you made are conflicting with mine. I'll try to resolve it.

**Comment by endreman0** [comment]
All better.

**Comment by BenP51** [comment]
Sweet


Sent by Outlook for Android





On Tue, May 26, 2015 at 3:42 PM -0700, "endreman0" <notifications@github.com> wrote:
All better.

---

**Comment by endreman0** [comment]
By the way, the issue with the broken CSS issue is a problem with transferring between two sites. If you take a look at `_config.yml` in the main site and my clone, the `url` and `baseurl` attributes are different. This is prepended to every link, so having my config in your repository (or vice versa, which I'm working on fixing right now) breaks all the links to stylesheets and scripts.

**Pull request merged**
